pipeline:
  syntax-check:
    image: container.zlab/dev-infra/tools:v1.11.0
    commands:
      - make check
    when:
      event: pull_request

  build:
    image: container.zlab/dev-infra/tools:v1.11.0
    secrets:
      - os_auth_url
      - os_tenant_name
      - os_username
      - os_password
      - os_domain_name
      - os_identity_api_version
    commands:
      - make validate
      - make image
      - make compress
      - make prune
    when:
      branch: [master, test]
      event: push

  test:
    image: container.zlab/dev-infra/tools:v1.11.0
    secrets:
      - os_auth_url
      - os_project_name
      - os_username
      - os_password
      - os_domain_name
      - google_credentials
      - ci_infra_config
    commands:
      - mkdir -p infra-init/ci
      - echo "$${CI_INFRA_CONFIG}" > infra-init/ci/config.env
      - make test
    when:
      branch: [master]
      event: push

  promote:
    image: container.zlab/dev-infra/tools:v1.11.0
    secrets:
      - os_auth_url
      - os_project_name
      - os_username
      - os_password
      - os_domain_name
      - os_identity_api_version
    commands:
      - make promote
    when:
      event: tag
