pipeline:
  github-release:
    image: container.zlab/dev-infra/tools
    secrets:
      - GITHUB_USER
      - GITHUB_TOKEN
    environment:
      - USER=drone
      - ZLAB_UNIT=corp
      - GITHUB_USER=$$GITHUB_USER
      - GITHUB_TOKEN=$$GITHUB_TOKEN
    commands:
      - make update-release
    when:
      event: tag
